# GET /profile
GET  http://localhost:3001/api/profile
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhZG1uIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjU5NTQyNTk5LCJleHAiOjE2NTk1NDI2NTl9.9VyhGwPeqzbZsOjSjpgl6XbWw2u8chH9en40ZeQE2mQ

###

POST http://localhost:3001/api/auth/register 
content-type: application/json

{
    "username":"uuserr",
    "password":"test_password",
    "email":"email@email122"
}

###

POST http://localhost:3001/api/auth/login 
content-type: application/json

# admin
# {
#     "username": "admin",
#     "password": "password"
# }

# regular user
{
    "username": "uuser",
    "password": "password"
}

###

GET http://localhost:3001/api/startParse
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InV1c2VyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NjExOTE3MDMsImV4cCI6MTY2MTE5MjIwM30.QAnmNVvsKapQMkPjfwgZT1T5ypPxqW2Uv_KsYu2zDsY

# {
#     "user":
#     {
#     "roles":["user"]
#     }
# }

###

GET http://localhost:3001/admin/controls 
content-type: application/json


{
"roles":"admin"
}

# {
#     "username": "john",
#     "password": "changeme"
# }